// DodoPayments Webhook Handler
// Called when a payment is completed. Logs the purchase.
// The license key is automatically created by DodoPayments — no action needed here.

export default async function handler(req, res) {
  if (req.method === 'OPTIONS') {
    return res.status(200).end();
  }

  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method Not Allowed' });
  }

  try {
    const event = req.body;

    // DodoPayments sends webhook events for payment completion
    // The license key is auto-generated by Dodo and delivered to the customer
    // We just log it here for our records
    console.log('[Webhook] Payment event received:', {
      type: event.type || 'unknown',
      customer_email: event.data?.customer?.email || 'unknown',
      product: event.data?.product?.name || 'cold mail',
      amount: event.data?.amount || 0,
      timestamp: new Date().toISOString()
    });

    return res.status(200).json({ received: true });

  } catch (error) {
    console.error('[Webhook] Error:', error.message);
    return res.status(500).json({ error: 'Webhook processing failed' });
  }
}
